### ISSUE TITLE
bower-components are installed in current-directory before update is completed

### ISSUE THREAD

**Issue by davalb** [platanus/capistrano-bower#6]
In my capistrano-log, I can see that bower is executed on the current-dir: 
`cd /var/www/.../current/app/webroot && /usr/bin/env bower install --quiet --config.interactive=false`
The problem is that this happens before the symlink is set to the new directory. Therefore all bower-dependencies are installed in the directory of the previous commit.
Is this a problem in my setup? Here is how I configured the bower_target_path: 
`set :bower_target_path, release_path.join("app/webroot")`
Thank you!

**Comment by davalb** [comment]
It turns out that this is not a problem of capistrano-bower. The bower_target_path is correct if it is loaded lazily. Here is how to do it:

```
set :bower_target_path, lambda { "#{release_path}/app/webroot" }
```

I found the solution in this answer: http://stackoverflow.com/questions/25850045/capistrano-returning-wrong-release-path

**Comment by blackjid** [comment]
:+1: great!
