### ISSUE TITLE
Check bower.json for changes

### ISSUE THREAD

**Issue by thaichors3000** [platanus/capistrano-bower#8]
Hi, I deploy a rails app. It works fine. But it always run bower install even though there is nothing changes in bower.json

I think it should just copy from previous release or current folder to its tmp build folder.

I used mina, but mina doesn't have mina-bower yet. So I wrote a task with solution above.

Do you agree to run only bower install when bower.json changes?

Thanks.

**Comment by blackjid** [comment]
Hey, well, 

what we've done in the past is setting a `.bowerrc` file with 

```json
{
  "directory": "vendor/assets/bower_components",
  "json": "bower.json"
}
```

and adding that directory to the `linked_dirs` option of capistrano, just like `vendor/bundle` https://github.com/capistrano/rails#symlinks

That way on every deploy the assets are shared, this means that when `bower install` gets executed it should only install what is different and if nothing was changed it should be fast enough.

I hope that helps

**Comment by thaichors3000** [comment]
Hi @blackjid 

I have taken a look in capistrano rails asset task. They always run rake assets:precompile.

Yes I agree with you. Checking for changes in bower.json doesn't benefit much. And also your solution on ```linked_dirs``` is better mine.

Thanks a lot.
